---
# config file for github actions
seed: 42
wrapper_directory: path/to/wrapper_directory
reference:
  genome: path/to/genome.file
  fasta: path/to/genome.fasta
input:
  length: 300
  merge: 50
  sliding: 50
samples: config/samples.tsv
