---
# config file for github actions
seed: 42
wrapper_directory: path/to/wrapper_directory
reference:
  genome: resources/example.fa.genome
  fasta: resources/example.fa
input:
  length: 300
  merge: 50
  sliding: 50
samples: config/samples.tsv
tests: config/tests.tsv
