---
# config file for github actions
seed: 42
wrapper_directory: path/to/wrapper_directory
reference:
  genome: /github/workspace/resources/example.fa.genome
  fasta: /github/workspace/resources/example.fa
input:
  length: 300
  merge: 50
  sliding: 50
samples: /github/workspace/config/samples_github.tsv
tests: /github/workspace/config/tests_github.tsv
