---
# config file for github actions
seed: 42
wrapper_directory: /data/gpfs-1/users/schubacm_c/work/projects/snakemake_wrappers
reference:
  genome: resources/example.fa.genome
  fasta: resources/example.fa
input:
  length: 200
  merge: 50
  sliding: 50
samples: config/samples.tsv
tests: config/tests.tsv
