---
seed: 42
wrapper_directory: resources/snakemake_wrappers
reference:
  genome: resources/example.fa.genome # genome file .genome
  fasta: resources/example.fa # genome file .fa
regression: true
adapters:
  left: AGGACCGGATCAACT
  right: CATTGCGTGAACCGA
training:
  model: standard
  loss: MSE
  augmentation: true
  augment_on: [16, 215]
prediction:
  augmentation: true
  augment_on: [16, 215]
  output_names: [MEAN]  # same header names as in input/labels, should have the size of output_size,
  output_size: 1  # number of outputs for the model (>1 it is a multitask model)
input:
  fasta: resources/demo/example_sequences.fa
  labels: resources/demo/example_labels.tsv  # BIN, ID (same as in fast), value1, value2, value3 (>1 value it is a multitask model)
satmut:
  sequence_length: 200
  step_size: 150
ism_regions:
  LDLR: chr19:11089268-11089498
  SORT1_1: chr1:109274785-109275015
  SORT1_2: chr1:109274986-109275216
