---
# config file for github actions
seed: 42
wrapper_directory: $GITHUB_WORKSPACE/wrappers
reference:
  genome: $GITHUB_WORKSPACE/resources/example.fa.genome
  fasta: $GITHUB_WORKSPACE/resources/example.fa
input:
  length: 300
  merge: 50
  sliding: 50
samples: $GITHUB_WORKSPACE/config/samples_github.tsv
tests: $GITHUB_WORKSPACE/config/tests_github.tsv
