---
__default__:
  time: "0-00:20"
  threads: 1
  mem: 2G
  queue: debug
  error: "logs/%x_%j_%N.err"
  output: "logs/%x_%j_%N.log"
sequence_selection_negative_background_widnows:
  time: "0-01:00"
  threads: 1
  mem: 10G
sequence_selection_negative_background_input:
  time: "0-01:00"
  threads: 1
  mem: 10G
sequence_selection_negative_background_sampler:
  time: "0-01:00"
  threads: 1
  mem: 20G
training_multitask:
  time: "5-00:00"
  mem: 30G
  threads: 25
  queue: gpu --gres=gpu:tesla:4
predict_fromFasta:
  time: "0-01:00"
  mem: 30G
  threads: 1
  queue: gpu --gres=gpu:tesla:1
