$schema: "http://json-schema.org/draft-04/schema#"

description: snakemake configuration file

type: object

# possible entries of the config file and which type they should be
properties:
  seed:
    type: integer
  wrapper_directory:
    type: string
  training:
    type: object
    properties:
      model:
        type: string
        enum: [standard, simplified, saluki]
        default: standard
      loss:
        type: string
        enum: [MSE, Huber, Poission, CategoricalCrossentropy]
        default: MSE
      augmentation:
        type: boolean
        default: false
      augment_on:
        type: array
        minitems: 2
        maxitems: 2
        items:
          type: integer
    default: {}
  prediction:
    type: object
    properties:
      output_names:
        type: array
        items:
          type: string
        default: ["MEAN"]
      output_size:
        type: integer
        default: 1
      augmentation:
        type: boolean
        default: false
      augment_on:
        type: array
        minitems: 2
        maxitems: 2
        items:
          type: integer
    default: {}
  reference:
    type: object
    properties:
      genome:
        type: string
      fasta:
        type: string
    required:
      - genome
      - fasta
  input:
    type: object
    properties:
      length:
        type: integer
        default: 300
      merge:
        type: integer
        default: 50
      sliding:
        type: integer
        default: 50
    required:
      - length
      - merge
      - sliding
  samples:
    type: string
  tests:
    type: string

# entries that have to be in the config file for successful validation
required:
  - training
  - prediction
  - seed
  - wrapper_directory
  - reference
  - samples
