---
# conda environments needed for the workflow should be stored here.
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bc
  - click
  - numpy
  - pandas
  - python
  - bedtools
  - htslib
